server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #使用微服务名访问，实现负载均衡
          predicates:
            - Path=/payment/** #断言,路径相匹配的进行路由
            #- After=2020-07-22T12:15:26.063+08:00[Asia/Shanghai] 在时间之后访问有效
            #- Before=2020-07-22T12:55:26.063+08:00[Asia/Shanghai] 在时间之前访问有效
            #- Cookie=username,hxq 必须有cookie username为hxq访问有效
#        - id: payment_routh3
#          uri: http://news.baidu.com
#          predicates:
#            - Path=/**

#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
#          filters:
#              # 熔断降级配置
#            - name: Hystrix
#              args:
#                name: default
#                fallbackUri: 'forward:/defaultFallback'


eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway9527
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

#降级
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE
#          thread:
#            timeoutInMilliseconds: 1000
#  shareSecurityContext: true
