server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hxqForJob/springcloud-config.git
          search-paths:
            - springcloud-configs
      label: master
  rabbitmq:
    host: 192.168.1.108
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: cloudConfig3344
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'